Repository distributedio/titan, pull requests merged in 2019-03, with the labels that each got.

#44 add set-design.md
  proposals/set-design.md
Labels: enhancement, proposal

#60 FlushDB and FlushAll failed
  command/server.go
  db/db.go
  db/kv.go
  go.mod
Labels: bug

#66 update mock
  tools/integration/titan.go
Labels: good first issue

#68 update Tikv sdk to 2.1.5
  db/store/store.go
  go.mod
Labels: good first issue
