Repository distributedio/titan, pull requests merged in 2019-01, with the labels that each got.

#13 Hash实现
  README.md
  bin/titan/main.go
  command/error.go
  command/hashes.go
  command/hashes_test.go
  command/init.go
  command/keys.go
  command/server.go
  command/test_test.go
  conf/config.go
  conf/titan.toml
  db/db.go
  db/db_test.go
  db/hash.go
  db/hash_test.go
  db/kv.go
  db/object.go
  db/test_test.go
  tools/integration/titan.go
Labels: enhancement, proposal

#35 Update tidb to the latest master
  go.mod
Labels: enhancement

#38 fixed nil pointer dereference issue caused by invalid last point
  db/tikvgc.go
Labels: bug

#41 Backoff TiKV SDK to release-2.1
  go.mod
Labels: enhancement

#21 add setbit command
  command/init.go
  command/strings.go
  command/strings_test.go
  db/db_test.go
  db/string.go
  db/string_test.go
  tools/autotest/auto.go
Labels: enhancement

#42 register sdk metrics
  metrics/prometheus.go
Labels: enhancement

#43 Fix: missing return
  command/connection.go
Labels: bug
