Repository distributedio/titan, pull requests merged in 2019-05, with the labels that each got.

#78 删除go.mod中对github.com/meitu/titan 的依赖
  go.mod
Labels: bug

#51 zset的设计proposal
  proposals/zset.md
Labels: enhancement, proposal

#57 Fix command missing in pipeline mode when close a connection
  client.go
Labels: bug

#71 Feature/Delete the Len field and MateSloat in the hash-meta
  command/command.go
  command/hashes.go
  command/hashes_test.go
  command/init.go
  command/keys.go
  command/server.go
  command/transactions.go
  db/db.go
  db/hash.go
  db/hash_test.go
  db/kv.go
  metrics/prometheus.go
Labels: enhancement

#79 Refactor sunion/sinter by minheap
  command/sets.go
Labels: enhancement
