Repository distributedio/titan, pull requests merged in 2019-11, with the labels that each got.

#151 fix(config): remove hash slot
  conf/config.go
  conf/titan.toml
  db/db.go
  db/db_test.go
Labels: bug

#154 docs: add the proposal guidelines
  proposals/README.md
Labels: docs

#155 refactor: rename Tikv to TiKV
  bin/titan/main.go
  command/test_test.go
  conf/config.go
  conf/mockconfig.go
  db/db.go
  db/db_test.go
  db/expire.go
  db/expire_test.go
  db/gc.go
  db/gc_test.go
  db/kv.go
  db/test_test.go
  db/tikvgc.go
  metrics/prometheus.go
  proposals/set-design-en.md
  tools/integration/titan.go
Labels: enhancement
