Repository distributedio/titan, pull requests merged in 2019-06, with the labels that each got.

#109 transfer continuous to distributedio
  bin/titan/main.go
  go.mod
Labels: enhancement

#111 add the commit message style guide
  docs/commit-message-style.md
Labels: docs

#115 Fixed the problem that the RemoveRepByMap function could not de-dupli…
  db/set.go
  db/set_test.go
Labels: bug
